Add comments
Anticvariat/hello pull request #16
Opened 2022-08-29 12:19 UTC by Anticvariat

2022-08-31 12:39 UTC, MaximStadnikov requested changes

2022-08-31 12:39 UTC, MaximStadnikov commented on app/controllers/comments_controller.rb
> +  def show
зачем тебе show метод?

2022-08-31 12:39 UTC, MaximStadnikov commented on app/models/comment.rb
> +  validates :comment, presence: true, length: { minimum: 10 }
мб тут должно быть body вместо comment?

2022-08-31 12:39 UTC, MaximStadnikov commented on app/views/articles/show.html.erb
> +    <% if comment.commenter != nil %>
зачем эта проверка, если у тебя стоит валидация на обязательное наличие комментатора?

2022-08-31 12:39 UTC, MaximStadnikov commented on app/views/articles/show.html.erb
> +<h2 class="mid title">Оставить комментарий</h2>
для удобства лучше вынести весь код снизу (тот, что касается комментариев) в отдельный partial и рендерить его в текущем файле

2022-08-31 12:39 UTC, MaximStadnikov commented on config/routes.rb
> +    resources :comments
тебе не нужны все методы для комментариев, поэтому надо явно здесь объявить только те, что ты используешь

2022-08-31 12:39 UTC, MaximStadnikov commented on spec/requests/comments_spec.rb
> +    pending "add some examples (or delete) #{__FILE__}"
пустые тесты только вводят в заблуждение, поэтому их стоит удалять. И вообще надо бы написать тесты для комментариев, чтобы проверить их работоспособность

2022-08-31 12:39 UTC, MaximStadnikov commented on app/views/articles/show.html.erb
> +      <%= form.text_field :commenter, value: (current_user.first_name if user_signed_in?), class: 'form-control', placeholder: 'Имя', required: true %>
Не хочешь ли ты запретить писать комментарии незарегистрированным пользователям? На мой взгляд это хорошая практика - побуждает пользователей регистрироваться, а так же защищает от наплыва анонимных троллей и "ддос" атак

2022-09-08 07:50 UTC, Anticvariat commented on app/views/articles/_comments.html.erb
> +    <% if comment.body != nil %>
без этой строчки в списке комментариев выводится пустой комментарий без автора

2022-09-08 07:50 UTC, Anticvariat commented on app/views/articles/_comments.html.erb
> +    <% if comment.body != nil %>
без этой строчки в списке комментариев выводится пустой комментарий без автора

2022-09-12 13:13 UTC, MaximStadnikov requested changes

2022-09-12 13:13 UTC, maximstadnikov commented on app/controllers/comments_controller.rb
> +    redirect_to article_path(@article) if @comment.save
а что делать, если `@comment.save` будет `false`?

2022-09-12 13:13 UTC, maximstadnikov commented on app/javascript/packs/comments_validations.js
> +button.addEventListener('click', (event) => {
проверь случай, если отправить форму, нажав клавишу Enter. Есть вероятность, что функция `isValid()` будет вызываться только при клике на кнопку, поэтому если ты засабмитишь форму другим способом, то валидации не будет

2022-09-12 13:13 UTC, maximstadnikov commented on db/migrate/20220912063925_fix_column_name.rb
> +class FixColumnName < ActiveRecord::Migration[6.0]
Зачем нужна эта миграция? Она сломает твое приложение, так как не найдет в таблице `Users` поле `author_id`. Миграции должны быть строгой последовательностью действий, без противоречий и недочетов. В предыдущих миграциях нет никакого упоминания о поле `author_id` и это ошибка

2022-09-12 13:13 UTC, maximstadnikov commented on db/migrate/20220912063925_fix_column_name.rb
> +  def self.up
Еще одна ошибка заключается в том, что ты не добавил метод `self.down`. Это нужно для того, чтобы приложение понимало, что делать, в случае `rails db:rollback`

2022-09-12 13:13 UTC, maximstadnikov commented on app/models/comment.rb
> +  validates :user_id, presence: true
эту валидацию можно убрать из модели, если в миграции добавить `null: false`

2022-09-12 13:13 UTC, MaximStadnikov commented on spec/features/comments/create_comment_spec.rb
> +      expect(page).to have_content user.first_name
Этот тест непонятен для меня
То-есть нужно более явно проверять, что ты написал комментарий. И так же, на мой взгляд, стоит проверить, правильно ли этот комментарий добавился

2022-09-12 13:13 UTC, MaximStadnikov commented on spec/features/comments/create_comment_spec.rb
> +      fill_in 'article[title]', with: 'test'
зачем в тесте, который называется "Create Comment", ты создаешь статью? Это лишние действия, которые, во-первых, не имеют смысла в контексте данного теста, во-вторых, это нагружает сам тест (увеличивает время его выполнения)

2022-09-14 09:29 UTC, Anticvariat commented on app/javascript/packs/comments_validations.js
> +button.addEventListener('click', (event) => {
работает, даже если отправлять форму по нажатию Enter

2022-09-14 09:30 UTC, Anticvariat commented on app/javascript/packs/comments_validations.js
> +button.addEventListener('click', (event) => {
> проверь случай, если отправить форму, нажав клавишу Enter. Есть вероятность, что функция `isValid()` будет вызываться только при клике на кнопку, поэтому если ты засабмитишь форму другим способом, то валидации не будет

работает, даже если отправлять форму по нажатию Enter

2022-09-14 11:12 UTC, MaximStadnikov requested changes

2022-09-14 11:12 UTC, MaximStadnikov commented on spec/features/comments/create_comment_spec.rb
> +      expect(section).to have_content user.first_name
тут также стоит проверить, что комментарий верно сохранился и ничего не перепуталось. То-есть что-то вроде такого:
`expect(section).to have_content 'comment with valid params'`

2022-09-14 11:23 UTC, MaximStadnikov approved these changes

2022-09-14 11:23 UTC, merged