Add rspec and capybara tests
Anticvariat/hello pull request #5
Opened 2022-08-02 11:52 UTC by Anticvariat

2022-08-04 11:59 UTC, sergeyantonov1 commented on spec/models/home_controller_spec.rb
> +  describe 'get index' do
По правилам, `describe` должен описывать либо класс, либо его методы. Подробнее можно почитать тут https://www.betterspecs.org/#describe
```suggestion
  describe '#index' do
```

2022-08-08 11:01 UTC, ArthurZaharov requested changes

2022-08-08 11:01 UTC, ArthurZaharov commented on .github/workflows/github-actions-demo.yml
> +name: GitHub Actions Demo
Зачем этот файл? Если он не часть этого ПР, то надо удалить

2022-08-08 11:01 UTC, ArthurZaharov commented on Gemfile
> +gem 'rails_12factor', group: :production
Хорошая структура Gemfile выглядит так
```
ruby '2.7.6'

# main gems
gem 'rails', '~> 6.0.5'
gem 'pg', '~> 1.1'

# other gems
...
```

2022-08-08 11:01 UTC, ArthurZaharov commented on Gemfile
> +gem 'faker'
Это гем для тестов, он не нужен в основном приложении. Надо перенести в группу test

2022-08-08 11:01 UTC, ArthurZaharov commented on Gemfile
> +gem 'test', '~> 1.0'
Что это за гем такой, для чего?

2022-08-08 11:01 UTC, ArthurZaharov commented on spec/features/articles/create_article_spec.rb
> +  it 'is valid' do
feature тесты пишутся сценариями
```
feature "Create Article" do
  scenario "Create Article with correct params" do
    ...
  end
end
```

Вот тут есть информация - https://github.com/teamcapybara/capybara#using-capybara-with-rspec

2022-08-08 11:01 UTC, ArthurZaharov commented on spec/models/home_controller_spec.rb
> +    it 'is valid' do
В it должно быт написано, что ты ожидаешь
```
it "returns OK status"
```

2022-08-08 12:06 UTC, ArthurZaharov approved these changes

2022-08-08 12:18 UTC, merged